### ISSUE TITLE
PRs take too long to land

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4740]
Pull requests take too long to land in our project. As of writing this issue, there are 79 open pull requests.

Potential causes (which could be broken into projects):
* CI issues: CI takes too long, CI is flaky, failing tests are hard to debug, tests are not granular, docker.io flakes and fails the build sometimes, toolchain rebuild takes _way_ too long
* Review issues: Waiting for feedback, too many people needed for review, too long to review easily, not clear which PRs folks need to review at what time

Projects:
* CODEOWNERs revamp (caused too many people to be notified so they don't know if they are actively requested)
	Exit Criteria:
	* Unrequired people should not be marked as required on a PR
* Moving away from CircleCI -- (propose something or run a meeting) Brandon
	Exit Criteria:
	* Tests are granular based on changed code (TODO: project level vs protocol, more granular = more work but faster)
    * TODO once problems and proposal is fleshed out
* Address flakiness process (and make it easy to mark things as flaky)
    Exit Criteria:
    * Process around unblocking flaky tests (either removed, not run, auto-rerun..)
    * Tests should document themselves as flaky
* Fix CI for external contributors 
    Should we dogfood external contributions?
	A couple people dogfooding??
    Exit Criteria:
    * All tests pass for PRs opened by non-core team members
 	* build-archive + build-macos fail

Action items:
- [ ] Break this into several projects -- All
- [ ] CODEOWNERs fix proposal -- Avery
- [ ] Moving away from circle -- Brandon
