### ISSUE TITLE
Stabilize develop

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#4744]
- [x] Merge release into develop (#4703)
- [x] Divide up ability to deploy networks from develop (#4749)
- [x] Port coda-automation work for bugspray network back into master (#4774)
- [x] Configure QA networks to fully saturate transaction per block (# snark workers = # leaves in a scan state) (#4758)
- [X] Fix runtime genesis timestamp prover error (#4757) (closed in favour of #4769)
- [ ] Fix early bootstrap forking (and validate in testnet) (#4750)
- [ ] Fix late catchup forking (and validate in testnet) (#4751)

### EXIT CRITERIA

Run a QA network with at 200 fish block producers which meets the following criteria:

- the testnet guardian runbook has been finalized and approved by the infrastructure team
- transactions per block is fully saturated (there is enough snark worker and transactions to do so)
- staged ledger proofs are being properly emitted
- some form of a "chaos monkey" script is run against the network periodically (to validate new nodes joining via bootstrap and network resilience to partial outages)
- the network runs without significant unresolvable forks or prover errors for at least 2 full epochs after the first staged ledger proof is emitted

**Comment by nholland94** [comment]
https://github.com/CodaProtocol/coda/pull/4703 merged the release branch back into develop.

**Comment by nholland94** [comment]
A network was run over the weekend which met some of the exit criteria (2 epochs, no forks or prover errors). Will run another network with full snark work saturation and chaos monkey scripts enabled.

**Comment by bkase** [comment]
Can we add to the exit criteria something along the lines of:

* A full production-esque (2 seeds, 5 block producers, etc + the discord bots + the Brandon's metric collection hack) network has been run for 2 full epochs

Just want to be cognizant that this hurt us last time. After the above, we should be ready to launch at a moments notice.

**Comment by nholland94** [comment]
Sure. I have been running with discord bots already. What's your metric collection hack and how do I deploy it?

**Comment by bkase** [comment]
> EDIT: are you saying we should run a 5 bp only network in addition to the 200 node network?

I think we should be confident that we can launch with the production configuration -- if the 200 node network is easy enough to tweak for the 5bp world maybe it's okay. Maybe we want to spin up a 5bp one where we only have half the stake if that's a potential weak point.

https://github.com/CodaProtocol/coda/pull/4650 this thing, but we can just run it manually on a compute engine instance, no need to build infrastructure around it since we believe it to be temporary until we fix archive node issues.

**Comment by nholland94** [comment]
Discussed offline, but we decided to keep these additional points off of the exit criteria for this team. These are certainly required before a release, but they do not need to explicitly block the disbandment of this team given that they are not directly related to protocol stabilization.

**Comment by nholland94** [comment]
There is a strong chance that we may pull in #4721 into this team as an additional epic.

**Comment by nholland94** [comment]
Currently running a new network which will fully satisfy the exit criteria for this epic (so long as it doesn't find any issues). Otherwise, all work on this epic is completed for the time being.

**Comment by nholland94** [comment]
We have successfully run a network that meets all of our exit criteria for this epic.
