### ISSUE TITLE
Network validation

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#4798]
- [ ] Specify validation requirements to be met before every release (#4793)
- [ ] Create initial script for automated validation of network (a reasonable subset of the release validation requirements) (#4794)
- [ ] Finalize testnet guardian runbook (#4795)

### EXIT CRITERIA

- there exists a specific checklist of X-team validation requirements to be met before every release
- the guardian runbook is reviewed and finalized
- there exists a validation service which is deployed alongside networks and is capable of notifying discord when validation fails
- the validation service is able to detect forks on the network
- the validation service is able to detect not enough transactions or snark work being included in blocks

**Comment by aneesharaines** [comment]
Just a nit, but for the first bullet of the exit criteria it would be good to specify that a it be a specific **documented** checklist

**Comment by dkijania** [comment]
looks like app is retired
