### ISSUE TITLE
Runtime configuration

### ISSUE THREAD

**Issue by mrmr1993** [CodaProtocol/coda#4829]
Runtime configuration is currently managed by `runtime_genesis_ledger.exe` and flags passed to the daemon. This causes some issues around configurability and behaviour that we would like to support.

### Overview

There are 3 kinds of constants that can be configured at compile time:
* 'runtime' constants
  - these do not affect the proving keys or the proofs for the snarks
  - e.g. `txpool_max_size`
* 'genesis' constants
  - these are encoded in the proofs proofs generated for each block, and so need to be set before creating the genesis proof for a chain
  - e.g. the genesis ledger
* 'proof system' constants
  - these affect the constraints for the blockchain proofs, and so need to be set before generating the proving/verification keys
  - e.g. ledger depth

We would like configurability of at least the genesis constants for test deployments, and of all classes of constants for the integration tests, all using the same binary.

#### Runtime constants

These should be handled by the daemon at runtime, as currently. Their handling should be separated from the genesis constants.

#### Genesis constants

These should be set to their default values at compile time, with the appropriate genesis proof generated. However, it is useful to be able to use e.g. a different genesis ledger with the same coda binary.

* By default, the compile-time values should be used.
* The variables should be configurable at runtime, via either flags or a configuration file.
  - These should trigger a proof-search: we should attempt to find an existing genesis proof for the configuration if one is cached on the system.
    + We should also search the o1-keys S3 bucket for the proofs, so that distributed networks can pull in the correct proof if they were not set up with it.
  - In order for genesis proofs to be easily found, we should identify them by the 'base hash': the hash of the genesis state, the hash accepted by the genesis proof as public input.
    + This also makes validation trivial: we can confirm that the genesis proof is as desired by verifying it against the hash with the compile-time verification keys.
  - When no proof is found, the daemon should (configurable by a flag) generate a genesis proof for the configuration, identifying it with the 'base hash' so that it can be recalled later.
    + There should also be a dedicated executable for this behaviour, replacing the existing `runtime_genesis_ledger.exe`
    + There should be an associated script that runs the executable and uploads the genesis proof to the S3 bucket.
* The configuration should be settable by a configuration directory, where a configuration file and genesis proof can be found, so that distributed nodes can be set up without having to fetch proofs from S3 etc.
  - This directory should be configurable with a flag.
* This should support a runtime `--proof-level` flag, where no proofs are fetched/generated/used for proof levels lower than `full`.
* Genesis ledger configuration should be modified to support
  - inline configuration (as part of the main configuration file)
  - separate configuration (as a dedicated file, overriding the configuration integrated into the main file)
  - 'named' ledgers, accessing one of the pre-defined ledgers from `Genesis_ledger`

#### Proof system constants

These should be set to their default values at compile-time, and associated with the appropriate proving/verification keys. However, for various integration tests, we would like these to be configurable.

* By default, and whenever the `--proof-level` is `full`, we should use the compile-time values.
  - We may wish to relax this to a key search in future, if we find ourselves wanting to configure these constants at deploy-time.
* For `--proof-level=check` and below, these variables should be configurable at runtime, via either flags or a configuration file.
  - This requires no search: we do not use keys for these proof levels.
  - For `--proof-level=full`, we should check that the values match the default values as a sanity check, failing otherwise.
* These should be managed separately from the genesis/runtime constants, to ensure they do not get conflated.

### Tasks

* [x] Lower `runtime_genesis_ledger.exe` functionality into a library, usable by the coda daemon and the dedicated executable.
  - [x] Configuration state logging.
* [x] Coda daemon flags.
  - [ ] Flag sharing between daemon and helper.
* [x] Naming according to the 'base hash' for configuration.
  - [x] Local naming.
  - [x] S3 naming.
* [x] Daemon genesis proof generation support.
* [x] Genesis proof generation+upload script.
* [x] Runtime configuration directory.
* [x] Improved genesis ledger configuration.
  - [x] Named ledgers.
  - [x] Inlining in configuration files.
  - [x] Flexible parsing (ignore unrecognised fields for notes, etc.)
  - [ ] Sensible default values.
* [x] Runtime genesis constants routing.
* [x] Runtime `proof-level`.
* [x] Runtime proof system constants routing.
* [ ] Nonconsensus configuration.
* [ ] Usage in integration tests.

**Comment by bkase** [comment]
Great! Thanks for fleshing this out.

A few questions:

1. Is the "main configuration file" part of what is currently "daemon.json"? Can it be part of that? There's a meeting on Thursday where a few different folks are chatting about what this could look like going forward, but wanted to call that out now.
2. This seems like a lot of work -- do you have a sense of what chunk of this work is worth prioritizing in the short term? To me, it seems like some genesis ledger work (library-ing, generating and loading specific ones later), and the proof system changes for proof-level-check variable changing seem very important. Proving/verification key re-generation we should for sure not worry about now (as you identified) -- maybe we can also punt on making parsing more flexible for genesis. Also, do we need to support proof regeneration or can we move more of the changing parameters to runtime? Is it more difficult to move the genesis ledger part of the genesis proof to runtime than it is to make genesis proofs swappable? Anyway, would love to hear what you think.

**Comment by mrmr1993** [comment]
> Is the "main configuration file" part of what is currently "daemon.json"? Can it be part of that?

I used 'main configuration file' to draw the distinction between `config.json` and (the auxiliary configuration file) `accounts.json`. The point there is to give us a unified place to define configs for the integration tests, which would necessarily include the genesis ledger.

 There is nothing stopping us from using a single config file for all of the different kinds of variables. For simplicity, I think we should, being careful to fail early and hard when the configuration doesn't make sense.

> Also, do we need to support proof regeneration or can we move more of the changing parameters to runtime?

Integration tests and deployments both seemed to warrant changeable genesis ledgers, which requires a new genesis proof.

> Is it more difficult to move the genesis ledger part of the genesis proof to runtime than it is to make genesis proofs swappable?

I'm not clear on what it would mean to 'move the genesis ledger part of the genesis proof to runtime', and it feels like a fundamentally dangerous idea to me.

> do you have a sense of what chunk of this work is worth prioritizing in the short term?

The routing of configuration variables is the most pressing, since everything else requires it. The runtime proof-level is done (#4833) which unblocks a lot of that.

We can cut some work by dropping either ease of deployments or single-binary integration tests, but otherwise we'll need most of it.

**Comment by bkase** [comment]
> I'm not clear on what it would mean to 'move the genesis ledger part of the genesis proof to runtime', and it feels like a fundamentally dangerous idea to me.

Makes sense, I suppose you're right.

> We can cut some work by dropping either ease of deployments or single-binary integration tests, but otherwise we'll need most of it.

Both those sound important!

Do you think you could give a rough estimate of how long this should take in total? And can you identify which chunks are parallelizable (once some of the other folks have cycles maybe we can go through it faster together)

**Comment by mrmr1993** [comment]
> Do you think you could give a rough estimate of how long this should take in total?

Most of the tasks are small and parallelisable. The constant routing is hard to estimate, but everything else should be doable in a day or two, not counting time taken to land PRs. Estimate **1 week** for this issue, to allow time for debugging etc if needed.

Btw, I suggest we punt on "Nonconsensus configuration" for now, since it's not necessary for our main goals in X-Force C.
