### ISSUE TITLE
Buildkite CI: Make copy-artifacts-to-cloud step work in the buildkite environment

### ISSUE THREAD

**Issue by 0x0I** [CodaProtocol/coda#5287]
Enable functional parity with CircleCI `copy-artifacts-to-cloud` [job](https://github.com/CodaProtocol/coda/blob/develop/.circleci/config.yml#L497) + `scripts`/[artifacts.sh](https://github.com/CodaProtocol/coda/blob/develop/scripts/artifacts.sh) using the Buildkite Dhall configuration rendering pipeline and operating within agent environments.

**Subtasks:**
* [x] Enable Buildkite agent GCP GCS read/write access (on provisioning)
* [x] Ensure auto-upload to appropriate CI GCS bucket
* [ ] Allow Dhall pipeline configs to express `artifact_paths` for *glob-based* auto-uploading

*References:*
- CircleCI [example](https://github.com/CodaProtocol/coda/blob/develop/.circleci/config.yml.jinja#L373) `Copy artifacts to cloud`
- [List SelectFiles.Type](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Lib/SelectFiles.dhall) for `artifact_paths` Base Command [Config](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Command/Base.dhall#L57) property addition
- Buildkite GCS uploads [docs](https://buildkite.com/docs/agent/v3/gcloud#uploading-artifacts-to-google-cloud-storage)

:link: https://github.com/CodaProtocol/coda/pull/5277
